name: Docker Build and Deploy

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - main
      - prod

env:
  IMAGE_NAME: thaddeusjiang/zipcodejp

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: thaddeusjiang
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Define Docker Tag
        id: prep
        run: |
          # github.ref_name maybe `13/merge`
          DOCKER_TAG=${GITHUB_REF_NAME//\//-}
          echo "docker_tag=${DOCKER_TAG}" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.prep.outputs.docker_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push image for prod(:latest)
        if: github.ref == 'refs/heads/prod'
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
